spring:
  datasource:
    url: jdbc:oracle:thin:@//테스트DB서버주소:1521/TESTDB
    username: 테스트DB계정
    password: 테스트DB비밀번호
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    database-platform: org.hibernate.dialect.Oracle12cDialect
    hibernate:
      ddl-auto: validate
  sql:
    init:
      mode: always
      continue-on-error: true
      schema-locations: classpath:schema-oracle.sql
      data-locations: 